import { createContext, useContext, useMemo, useState } from 'react'
import type { ReactNode } from 'react'

export type Locale = 'es' | 'en'

type TranslationMap = Record<Locale, Record<string, string>>

const translations: TranslationMap = {
  es: {
    homeTitle: 'Bienvenido a EduPilot',
    homeSubtitle:
      'Una plataforma moderna preparada para múltiples dashboards y accesos basados en roles.',
    homeCta: 'Iniciar sesión',
    languageLabel: 'Idioma',
    loginTitle: 'Iniciar sesión',
    loginSubtitle: 'Accede con tu usuario o correo electrónico para continuar.',
    usernameLabel: 'Usuario o correo',
    passwordLabel: 'Contraseña',
    rememberMe: 'Recordarme',
    signIn: 'Entrar',
    forgotPassword: '¿Olvidaste tu contraseña?',
    portalTitle: 'Dashboard',
    portalSubtitle:
      'Estructura lista para mostrar módulos dinámicos por rol y configuraciones de menú.',
    logout: 'Cerrar sesión',
    welcome: 'Bienvenido',
    heroCta: 'Explorar dashboards',
    globalSettingsTitle: 'Configuración global',
    globalSettingsSubtitle: 'Administra módulos y accesos del sistema desde un solo lugar.',
    modulesCatalogTab: 'Catálogo de módulos',
    modulesCatalogDescription: 'Lista de módulos habilitados en el sistema.',
    modulesCatalogEmpty: 'No hay módulos disponibles para mostrar.',
    moduleEnabledLabel: 'Activo',
    footerText: 'EduPilot © 2025. Todos los derechos reservados.',
    wrongCredentials: 'Credenciales incorrectas. Verifica tus datos.',
    serviceUnavailable: 'El servicio no está disponible en este momento.',
    defaultError: 'Ocurrió un error inesperado.',
    loginPageTitle: 'Una nueva forma de vivir la experiencia escolar.',
    schoolsTitle: 'Escuelas',
    schoolsSubtitle: 'Consulta el catálogo de escuelas y navega a los detalles.',
    schoolsBreadcrumbLabel: 'Escuelas',
    schoolDetailsBreadcrumbLabel: 'Detalle de escuela',
    schoolsIdColumn: 'ID',
    schoolsNameColumn: 'Nombre comercial',
    schoolsPlanColumn: 'Plan',
    schoolsStatusColumn: 'Estatus',
    schoolsTypeColumn: 'Tipo',
    schoolsParentType: 'Escuela matriz',
    schoolsChildType: 'Sede',
    tableResults: 'Resultados',
    tablePageLabel: 'Página',
    tablePageOf: 'de',
    tablePageSize: 'Tamaño',
    tableRowsPerPage: 'Filas por página',
    tableLoading: 'Cargando información...',
    tableNoData: 'No hay registros para mostrar',
    tablePrev: 'Anterior',
    tableNext: 'Siguiente',
    tableActions: 'Acciones',
    viewDetails: 'Ver detalles',
    selectPlaceholder: 'Selecciona una opción',
    rolesPermissionsTitle: 'Roles y permisos',
    rolesPermissionsSubtitle: 'Elige la escuela y rol para revisar los accesos permitidos.',
    rolesPermissionsHelper: 'Cada escuela puede tener roles distintos y permisos personalizados.',
    selectSchoolLabel: 'Selecciona una escuela',
    selectRoleLabel: 'Selecciona un rol',
    selectGroupLabel: 'Selecciona un grupo',
    noDescription: 'Sin descripción disponible',
    permissionsTableTitle: 'Permisos del rol',
    permissionsTableSubtitle: 'Niveles de acceso por módulo para el rol seleccionado.',
    selectRolePrompt: 'Selecciona un rol para consultar los permisos.',
    moduleColumn: 'Módulo',
    permissionCreate: 'Crear',
    permissionRead: 'Leer',
    permissionUpdate: 'Actualizar',
    permissionDelete: 'Eliminar',
    permissionAllowed: 'Permitido',
    permissionDenied: 'Restringido',
    addPermissionButton: 'Añadir acceso a módulo',
    addPermissionFormTitle: 'Agregar permisos a un nuevo módulo',
    addPermissionFormDescription: 'Selecciona un módulo y define los accesos para el rol elegido.',
    selectModuleLabel: 'Selecciona un módulo',
    noAvailableModules: 'No hay módulos adicionales disponibles.',
    renew: 'Renueva',
    students: 'Alumnos',
    classes: 'Grupos',
    schoolOverviewTab: 'Visión General',
    schoolDetailsTab: 'Detalles de la escuela',
    schoolBillingTab: 'Plan y facturación',
    schoolSettingsTab: 'Configuración',
    schoolStructureTab: 'Estructura (Sedes)',
    schoolPlanBadge: 'Plan',
    schoolStatusBadge: 'Estatus',
    schoolAccessLabel: 'Acceso a plataforma',
    schoolEditButton: 'Editar detalles',
    schoolTeachersCard: 'Profesores',
    schoolAdminsCard: 'Administradores',
    schoolCampusesCard: 'Escuelas hijas',
    schoolBaseLimit: 'Límite base',
    schoolOverviewTitle: 'Información de contacto',
    schoolPlanTitle: 'Plan contratado',
    schoolNextBilling: 'Próxima facturación',
    schoolPreviousPeriods: 'Periodos previos',
    schoolPaymentsEmpty: 'No hay registros de pago.',
    schoolModulesTitle: 'Módulos habilitados',
    schoolRolesTitle: 'Roles creados por la escuela',
    schoolStructureTitle: 'Escuelas hijas (Campus)',
    schoolViewDetail: 'Ver detalle',
    schoolStatusActive: 'Activo',
    schoolStatusInactive: 'Inactivo',
    schoolLocationLabel: 'Ubicación',
    schoolIdLabel: 'ID',
    schoolPlanStatusLabel: 'Estatus del plan',
    schoolDetailsTitle: 'Información general de la escuela',
    schoolDetailsLocationTitle: 'Ubicación y contacto',
    schoolCommercialNameLabel: 'Nombre comercial',
    schoolBusinessNameLabel: 'Razón social',
    schoolTaxIdLabel: 'RFC',
    schoolDescriptionLabel: 'Descripción',
    schoolCreationDateLabel: 'Fecha de creación',
    schoolMaxDebtLabel: 'Deuda máxima permitida',
    schoolDefaultTuitionLabel: 'Colegiatura base',
    schoolContactEmail: 'Correo',
    schoolContactPhone: 'Teléfono',
    schoolAddressLabel: 'Dirección',
    schoolNoData: 'Sin información',
    schoolStudentsCard: 'Alumnos',
    ocupied: 'Ocupado',
    email: 'Correo Electrónico',
    main_contact: 'Contacto Principal',
    startDate: 'Fecha inicial',
    results: 'Resultados',
    searchStudentByName: 'Buscar estudiante por nombre',
    searchByGroup: 'Buscar por grupo',
    searchByStudent: 'Buscar por estudiante',
    studentsGroups: 'Alumnos y Grupos',
    tuitions: 'Colegiaturas',
    paymentRequests: 'Solicitudes de Pago',
    historyTab: 'Historial',
    scheduledTab: 'Programadas',
    createPaymentRequest: 'Crear Nueva Solicitud',
    singleRequest: 'Solicitud Única',
    singleRequestDescription: 'Un cobro específico para uno o más alumnos',
    scheduledRequest: 'Solicitud Programada',
    scheduledRequestDescription: 'Un cobro recurrente (mes, año, etc)',
    applyScopeRequired: 'Selecciona a quién se aplicará la solicitud de pago.',
    uploadResultTitle: 'Resultado de creación de solicitudes',
    uploadResultSummary: 'Resumen de creación',
    uploadResultListTitle: 'Detalle de resultados',
    goBack: 'Regresar',
    downloadReport: 'Descargar reporte',
    createdCount: 'Solicitudes creadas',
    duplicateCount: 'Duplicados',
    noResultsAvailable: 'No hay resultados disponibles.',
    scheduledRequestsPlaceholder: 'Las solicitudes programadas estarán disponibles pronto.',
    active: 'Activa',
    inactive: 'Inactiva',
    pause: 'Pausar',
    editRule: 'Editar regla',
    financialConfiguration: 'Configuración financiera',
    baseAmount: 'Monto base',
    lateFeeCharge: 'Recargo por mora',
    internalNote: 'Nota interna',
    assignment: 'Asignación',
    assignedGroup: 'Grupo asignado',
    viewStudents: 'Ver alumnos',
    recentExecutions: 'Últimas ejecuciones',
    date: 'Fecha',
    generatedRequests: 'Generados',
    requests: 'solicitudes',
    viewExecutionDetail: 'Ver detalle de ejecución',
    schedule: 'Programación',
    frequency: 'Frecuencia',
    every: 'Cada',
    nextExecution: 'Próxima ejecución',
    dateInPastPending: 'Fecha en el pasado (Pendiente)',
    start: 'Inicio',
    end: 'Fin',
    undefinedEnd: 'Indefinido',
    chargeConditions: 'Condiciones de cobro',
    paymentWindow: 'Ventana de pago',
    daysWithoutLateFee: 'Días para pagar sin mora',
    createdShort: 'Creado',
    lastUpdatedShort: 'Última mod.',
    deleteRule: 'Eliminar regla',
    referenceDate: 'Fecha de referencia',
    periodicity: 'Periodicidad',
    createdRequests: 'Solicitudes creadas',
    duplicates: 'Duplicados',
    days: 'días',
    requestedAmount: 'Monto solicitado',
    payments: 'Pagos',
    paymentsFinance: 'Pagos y Finanzas',
    student: 'Estudiante',
    paymentType: 'Concepto',
    concept: 'Concepto',
    amount: 'Monto',
    status: 'Estatus',
    paymentThrough: 'Método de pago',
    paymentReference: 'Referencia',
    paymentDate: 'Fecha de pago',
    paymentMonth: 'Mes de pago',
    comments: 'Comentarios',
    receipt: 'Comprobante',
    viewReceipt: 'Ver comprobante',
    removeReceipt: 'Eliminar',
    uploadReceipt: 'Arrastra y suelta el comprobante o selecciona un archivo',
    chooseFile: 'Elegir archivo',
    dropInstruction: 'También puedes hacer clic para seleccionar un archivo',
    activityLog: 'Registro de actividad',
    noLogs: 'No hay registros de actividad para este pago.',
    paymentInformation: 'Detalle del pago',
    paymentRequestInformation: 'Detalle de la solicitud',
    paymentSummary: 'Resumen de pagos',
    totalPaid: 'Total pagado',
    latePeriods: 'Periodos con recargo',
    lateFeeTotal: 'Total de recargos',
    lateFee: 'Recargos',
    late_fee: 'Recargos',
    fee_type: 'Tipo de recargo',
    late_fee_frequency: 'Frecuencia de recargo (días)',
    accumulatedFees: 'Cargos acumulados',
    pendingPayment: 'Pendiente de pago',
    paymentsList: 'Pagos de la solicitud',
    breakdownTab: 'Desglose',
    activityAndComments: 'Actividad y comentarios',
    initialPaymentRequest: 'Solicitud inicial',
    paymentLabel: 'Pago',
    balance: 'Saldo',
    partialPayment: 'Pago parcial',
    partial_payment: 'Pago parcial',
    due_date: 'Fecha límite',
    pay_by: 'Fecha límite',
    studentInformation: 'Información del alumno',
    paymentDetail: 'Detalle del pago',
    tuitionPaymentDetail: 'Detalle de pagos de colegiatura',
    paymentRequest: 'Solicitud de pago',
    viewPaymentRequest: 'Ver solicitud de pago',
    registeredPayments: 'Pagos registrados',
    noPaymentsRegistered: 'No hay pagos registrados',
    totalAmount: 'Monto total',
    print: 'Imprimir',
    edit: 'Editar',
    approve: 'Aprobar',
    reject: 'Rechazar',
    phone: 'Teléfono',
    noInformation: 'Sin información',
    paymentRequestDetail: 'Detalle de solicitud de pago',
    paymentRequestPlaceholder: 'La página de detalle para la solicitud #{id} estará disponible pronto.',
    loadingRequest: 'Cargando solicitud...',
    groupLabel: 'Grupo: {{group}} · Nivel: {{level}} · Generación: {{generation}}',
    payment_concept_id: 'Concepto de pago',
    payment_month: 'Mes de colegiatura',
    payment_status_id: 'Estatus del pago',
    validated_by_user_id: 'Validado por',
    validated_at: 'Fecha de validación',
    created_at: 'Fecha de creación',
    updated_at: 'Fecha de actualización',
    payment_request_id: 'Solicitud de pago',
    payment_through_id: 'Método de pago',
    receipt_path: 'Recibo',
    receipt_file_name: 'Nombre de recibo',
    payment_date: 'Fecha de pago',
    close: 'Cerrar',
    addPayment: 'Añadir pago',
    noPermissionTitle: 'Sin permisos',
    noPermissionDescription: 'No tienes los permisos necesarios para acceder a esta sección. Por favor, contacta al administrador.',
    noReceiptPermission: 'No tienes permisos para cargar o modificar el comprobante.',
    confirmRejectPayment: '¿Estás seguro que quieres rechazar este pago?',
    cancel: 'Cancelar',
    accept: 'Aceptar',
    confirm: 'Confirmar',
    save: 'Guardar',
    saving: 'Guardando...',
    printerSettingsTitle: 'Configuración de impresora',
    printerSettingsDescription: 'Configura una impresora de tickets cuando uses la aplicación de escritorio.',
    printerNotAvailableBrowser: 'La impresión está disponible únicamente en la aplicación de escritorio.',
    printerNotAvailableDesktop: 'La impresión no está disponible actualmente.',
    printerPermissionRequired: 'No hay permisos para usar la impresora. Revisa los permisos del dispositivo.',
    printerBridgeMissingFeatures: 'La integración de impresión no está lista en esta instalación.',
    printerLoading: 'Cargando impresoras...',
    printerEmptyList: 'No se encontraron impresoras. Conecta o instala una impresora e inténtalo de nuevo.',
    printerDropdownLabel: 'Impresora de recibos',
    printerDefaultSuffix: 'predeterminada',
    printerSaveButton: 'Guardar selección',
    printerTestButton: 'Impresión de prueba',
    printerTesting: 'Enviando prueba...',
    areYouSureCloseRequest: '¿Estás seguro que deseas cerrar esta solicitud?',
    areYouSureCancelRequest: '¿Estás seguro que deseas cancelar esta solicitud?',
    school: 'Escuela',
    scholarLevel: 'Nivel escolar',
    metaSchoolCard: 'Agrega o actualiza la información escolar.',
    name: 'Nombre',
    firstName: 'Nombre',
    lastNameFather: 'Apellido paterno',
    lastNameMother: 'Apellido materno',
    birthDate: 'Fecha de nacimiento',
    phoneNumber: 'Número telefónico',
    taxId: 'RFC',
    curp: 'CURP',
    institutionalEmail: 'Correo institucional',
    personalEmail: 'Correo personal',
    street: 'Calle',
    extNumber: 'Número exterior',
    intNumber: 'Número interior',
    suburb: 'Colonia',
    locality: 'Localidad',
    municipality: 'Municipio',
    state: 'Estado',
    reference: 'Referencia',
    enrollment: 'Matrícula',
    mainData: 'Datos principales',
    address: 'Dirección',
    addressHelper: 'Dirección del alumno.',
    generation: 'Generación',
    class: 'Grupo',
    level: 'Nivel',
    'status-1': 'Sin validar',
    'status-2': 'Validación pendiente',
    'status-3': 'Validado',
    'status-4': 'Rechazado',
    'status-5': 'Pagado',
    'status-6': 'Sin pagar',
    'status-7': 'Cerrado',
    'status-8': 'Cancelado',
    'partialPayment-0': 'No',
    'partialPayment-1': 'Sí',
    success: 'Éxito',
    warning: 'Advertencia',
    neutral: 'Sin estado',
    logsTitle: 'Historial de ejecuciones',
    registerPaymentTitle: 'Registrar pago',
    registerPaymentDescription: 'Ingresa la información del pago para continuar.',
    enterValidAmount: 'Ingresa un monto válido',
    amountMustCoverPending: 'El monto debe cubrir el pendiente.',
    paymentMethodRequired: 'Selecciona un método de pago',
    noActiveSession: 'No hay sesión activa',
    paymentRegisterError: 'No se pudo registrar el pago',
    paymentRegisterSuccess: 'Pago registrado correctamente',
    printTicketPromptTitle: '¿Imprimir ticket?',
    printTicketPromptText: 'El pago se registró correctamente. ¿Deseas imprimir el ticket?',
    printTicketConfirm: 'Imprimir ticket',
    printTicketSkip: 'No imprimir',
    printTicketSuccessTitle: 'Ticket enviado',
    printTicketSuccess: 'El ticket fue enviado a la impresora.',
    printTicketErrorTitle: 'No se pudo imprimir',
    printTicketError: 'Ocurrió un error al enviar el ticket a la impresora.',
    printTicketUnavailable: 'La impresión está disponible solo en la app de escritorio o no hay impresora configurada.',
    paymentRegisterUnexpected: 'Ocurrió un error al registrar el pago',
    registerPayment: 'Registrar pago',
    registeringPayment: 'Registrando...',
    addAdditionalInformation: 'Agrega información adicional',
    selectedFile: 'Archivo seleccionado',
    createManualPayment: 'Crear pago manual',
    createManualPaymentDescription: 'Registra un pago llenando todos los campos.',
    studentRequired: 'Selecciona un alumno',
    paymentConceptRequired: 'Selecciona un concepto de pago',
    paymentMonthRequired: 'Selecciona el mes de pago',
    createPayment: 'Crear pago',
    register: 'Matrícula',
    group: 'Grupo',
    username: 'Usuario',
    password: 'Contraseña',
    clear: 'Limpiar',
    searching: 'Buscando...',
    yes: 'Sí',
    no: 'No',
    scheduleRequest: 'Agendar Solicitud',
    scheduleRequestDescription: 'Crea reglas programadas de pago',
    createSingleRequest: 'Crea una Solicitud',
    createSingleRequestDescription: 'Crea una solicitud de pago',
    updatePermissionTitle: '¿Estás seguro que deseas cambiar los permisos?',
    updatePermissionConfirmation: 'Puedes volver a cambiarlos en cualquier momento.',
    createClass: 'Crear Grupo',
    createStudent: 'Crear Estudiante',
    studentsBulkUploadTitle: 'Carga masiva de estudiantes',
    studentsBulkUploadSubtitle: 'Sube un archivo CSV para validar y crear estudiantes.',
    studentsBulkUploadInvalidFile: 'Solo se aceptan archivos CSV.',
    studentsBulkUploadEmptyFile: 'El archivo está vacío.',
    studentsBulkUploadHeaderError: 'El archivo no contiene los encabezados requeridos.',
    studentsBulkUploadLimitError: 'El archivo solo puede contener hasta 100 registros.',
    studentsBulkUploadDrag: 'Arrastra y suelta tu archivo CSV aquí',
    studentsBulkUploadSelect: 'O haz clic para seleccionar un archivo.',
    studentsBulkUploadDownload: 'Descargar plantilla',
    studentsBulkUploadReport: 'Descargar reporte',
    studentsBulkUploadValid: '{count} válidos',
    studentsBulkUploadInvalid: '{count} con errores',
    studentsBulkUploadValidating: 'Validando...',
    studentsBulkUploadCreate: 'Crear alumnos válidos',
    studentsBulkUploadCreating: 'Creando...',
    studentsBulkUploadRequired: 'El campo {field} es obligatorio.',
    studentsBulkUploadDuplicate: '{field} duplicado en el archivo.',
    studentsBulkUploadValidationError: 'No se pudo validar el registro en el servidor.',
    studentsBulkUploadExists: 'El registro ya existe en el servidor.',
    studentsBulkUploadNoValid: 'No hay registros válidos qué crear.',
    studentsBulkUploadHideLog: 'Ocultar log',
    studentsBulkUploadShowLog: 'Mostrar log',
    studentsBulkUploadRow: 'Renglón {row}',
    studentsBulkUploadMixedTitle: 'Hay registros con errores',
    studentsBulkUploadMixedMessage: 'Se crearán solo los registros válidos. ¿Deseas continuar?',
    studentsBulkUploadCreateSuccess: 'Registros creados exitosamente.',
    studentsBulkUploadCreateError: 'No se pudieron crear los registros.',
    studentsBulkUploadStepsTitle: 'Pasos para la carga',
    studentsBulkUploadStepSchoolTitle: 'Selecciona la escuela',
    studentsBulkUploadStepSchoolDescription: 'Elige la escuela para obtener la lista de grupos disponibles.',
    studentsBulkUploadStepGroupTitle: 'Selecciona el grupo',
    studentsBulkUploadStepGroupDescription: 'Define el grupo que se asignará a todos los alumnos cargados.',
    studentsBulkUploadStepTemplateTitle: 'Descarga el formato',
    studentsBulkUploadStepTemplateDescription: 'Utiliza el archivo CSV de referencia para respetar el formato correcto.',
    studentsBulkUploadStepUploadTitle: 'Sube el archivo CSV',
    studentsBulkUploadStepUploadDescription: 'Arrastra o selecciona un archivo con máximo 100 registros.',
    studentsBulkUploadHelper: 'Recuerda completar todos los campos obligatorios marcados con *.',

  },
  en: {
    homeTitle: 'Welcome to EduPilot',
    homeSubtitle:
      'A modern platform prepared for multiple dashboards and role-based access.',
    homeCta: 'Log in',
    languageLabel: 'Language',
    loginTitle: 'Sign in',
    loginSubtitle: 'Use your username or email address to continue.',
    usernameLabel: 'Username or email',
    passwordLabel: 'Password',
    rememberMe: 'Remember me',
    signIn: 'Sign in',
    forgotPassword: 'Forgot password?',
    portalTitle: 'Main dashboard',
    portalSubtitle:
      'Layout ready to display dynamic role-based modules and menu configuration.',
    logout: 'Log out',
    welcome: 'Welcome',
    heroCta: 'Explore dashboards',
    globalSettingsTitle: 'Global settings',
    globalSettingsSubtitle: 'Manage system modules and access from a single place.',
    modulesCatalogTab: 'Modules catalog',
    modulesCatalogDescription: 'List of enabled modules across the platform.',
    modulesCatalogEmpty: 'There are no modules to display.',
    moduleEnabledLabel: 'Enabled',
    footerText: 'EduPilot © 2025. All rights reserved.',
    wrongCredentials: 'Wrong credentials. Please try again.',
    serviceUnavailable: 'The service is unavailable right now.',
    defaultError: 'An unexpected error occurred.',
    loginPageTitle: 'A new way to live the school experience.',
    schoolsTitle: 'Schools',
    schoolsSubtitle: 'Browse the school catalog and open their details.',
    schoolsBreadcrumbLabel: 'Schools',
    schoolDetailsBreadcrumbLabel: 'School detail',
    schoolsIdColumn: 'ID',
    schoolsNameColumn: 'Commercial name',
    schoolsPlanColumn: 'Plan',
    schoolsStatusColumn: 'Status',
    schoolsTypeColumn: 'Type',
    schoolsParentType: 'Main school',
    schoolsChildType: 'Campus',
    tableResults: 'Results',
    tablePageLabel: 'Page',
    tablePageOf: 'of',
    tablePageSize: 'Size',
    tableRowsPerPage: 'Rows per page',
    tableLoading: 'Loading data...',
    tableNoData: 'No records to display',
    tablePrev: 'Previous',
    tableNext: 'Next',
    tableActions: 'Actions',
    viewDetails: 'View details',
    selectPlaceholder: 'Choose an option',
    rolesPermissionsTitle: 'Roles and permissions',
    rolesPermissionsSubtitle: 'Pick a school and role to review allowed access.',
    rolesPermissionsHelper: 'Each school can define its own roles and module permissions.',
    selectSchoolLabel: 'Select a school',
    selectRoleLabel: 'Select a role',
    selectGroupLabel: 'Select a group',
    noDescription: 'No description available',
    permissionsTableTitle: 'Role permissions',
    permissionsTableSubtitle: 'Access levels per module for the selected role.',
    selectRolePrompt: 'Select a role to view permissions.',
    moduleColumn: 'Module',
    permissionCreate: 'Create',
    permissionRead: 'Read',
    permissionUpdate: 'Update',
    permissionDelete: 'Delete',
    permissionAllowed: 'Allowed',
    permissionDenied: 'Restricted',
    addPermissionButton: 'Add module access',
    addPermissionFormTitle: 'Grant permissions to a new module',
    addPermissionFormDescription: 'Choose a module and set the access levels for the selected role.',
    selectModuleLabel: 'Select a module',
    noAvailableModules: 'No additional modules available.',
    renew: 'Renew',
    students: 'Students',
    classes: 'Classes',
    schoolOverviewTab: 'Overview',
    schoolDetailsTab: 'School details',
    schoolBillingTab: 'Plan & billing',
    schoolSettingsTab: 'Configuration',
    schoolStructureTab: 'Structure (Campuses)',
    schoolPlanBadge: 'Plan',
    schoolStatusBadge: 'Status',
    schoolAccessLabel: 'Platform access',
    schoolEditButton: 'Edit details',
    schoolTeachersCard: 'Teachers',
    schoolAdminsCard: 'Admins',
    schoolCampusesCard: 'Child schools',
    schoolBaseLimit: 'Base limit',
    schoolOverviewTitle: 'Contact information',
    schoolPlanTitle: 'Current plan',
    schoolNextBilling: 'Next billing',
    schoolPreviousPeriods: 'Previous periods',
    schoolPaymentsEmpty: 'There are no payment records.',
    schoolModulesTitle: 'Enabled modules',
    schoolRolesTitle: 'School roles created',
    schoolStructureTitle: 'Child schools (Campuses)',
    schoolViewDetail: 'View detail',
    schoolStatusActive: 'Active',
    schoolStatusInactive: 'Inactive',
    schoolLocationLabel: 'Location',
    schoolIdLabel: 'ID',
    schoolPlanStatusLabel: 'Plan status',
    schoolDetailsTitle: 'School general information',
    schoolDetailsLocationTitle: 'Location & contact',
    schoolCommercialNameLabel: 'Commercial name',
    schoolBusinessNameLabel: 'Business name',
    schoolTaxIdLabel: 'Tax ID',
    schoolDescriptionLabel: 'Description',
    schoolCreationDateLabel: 'Creation date',
    schoolMaxDebtLabel: 'Maximum allowed debt',
    schoolDefaultTuitionLabel: 'Base tuition',
    schoolContactEmail: 'Email',
    schoolContactPhone: 'Phone',
    schoolAddressLabel: 'Address',
    schoolNoData: 'No information',
    schoolStudentsCard: 'Students',
    ocupied: 'Ocupied',
    email: 'Email',
    main_contact: 'Main contact',
    startDate: 'Start date',
    results: 'Resultados',
    searchStudentByName: 'Search student by name',
    searchByGroup: 'Search by group',
    searchByStudent: 'Search by student',
    studentsGroups: 'Students and Classes',
    tuitions: 'Tuitions',
    paymentRequests: 'Payment Requests',
    historyTab: 'History',
    scheduledTab: 'Scheduled',
    createPaymentRequest: 'Create New Request',
    singleRequest: 'Single Request',
    singleRequestDescription: 'A specific charge for one or more students',
    scheduledRequest: 'Scheduled Request',
    scheduledRequestDescription: 'A recurring charge (month, year, etc.)',
    applyScopeRequired: 'Select who the payment request applies to.',
    uploadResultTitle: 'Payment request creation result',
    uploadResultSummary: 'Creation summary',
    uploadResultListTitle: 'Result details',
    goBack: 'Go back',
    downloadReport: 'Download report',
    createdCount: 'Created requests',
    duplicateCount: 'Duplicates',
    noResultsAvailable: 'No results available.',
    scheduledRequestsPlaceholder: 'Scheduled payment requests will be available soon.',
    active: 'Active',
    inactive: 'Inactive',
    pause: 'Pause',
    editRule: 'Edit rule',
    financialConfiguration: 'Financial configuration',
    baseAmount: 'Base amount',
    lateFeeCharge: 'Late fee',
    internalNote: 'Internal note',
    assignment: 'Assignment',
    assignedGroup: 'Assigned group',
    viewStudents: 'View students',
    recentExecutions: 'Latest runs',
    date: 'Date',
    generatedRequests: 'Generated',
    requests: 'requests',
    viewExecutionDetail: 'View execution detail',
    schedule: 'Schedule',
    frequency: 'Frequency',
    every: 'Every',
    nextExecution: 'Next run',
    dateInPastPending: 'Date in the past (Pending)',
    start: 'Start',
    end: 'End',
    undefinedEnd: 'No end date',
    chargeConditions: 'Charge conditions',
    paymentWindow: 'Payment window',
    daysWithoutLateFee: 'Days to pay without late fee',
    createdShort: 'Created',
    lastUpdatedShort: 'Last update',
    deleteRule: 'Delete rule',
    referenceDate: 'Reference date',
    periodicity: 'Periodicity',
    createdRequests: 'Created requests',
    duplicates: 'Duplicates',
    days: 'days',
    requestedAmount: 'Requested amount',
    payments: 'Payments',
    paymentsFinance: 'Payments and Finance',
    student: 'Student',
    paymentType: 'Concept',
    concept: 'Concept',
    amount: 'Amount',
    status: 'Status',
    paymentThrough: 'Payment method',
    paymentReference: 'Reference',
    paymentDate: 'Payment date',
    paymentMonth: 'Payment month',
    comments: 'Comments',
    receipt: 'Receipt',
    viewReceipt: 'View receipt',
    removeReceipt: 'Remove',
    uploadReceipt: 'Drag and drop the receipt or select a file',
    chooseFile: 'Choose file',
    dropInstruction: 'You can also click to select a file',
    activityLog: 'Activity log',
    noLogs: 'There are no activity records for this payment.',
    paymentInformation: 'Payment details',
    paymentRequestInformation: 'Request details',
    paymentSummary: 'Payment summary',
    totalPaid: 'Total paid',
    latePeriods: 'Late periods',
    lateFeeTotal: 'Total late fees',
    lateFee: 'Late fee',
    late_fee: 'Late fee',
    fee_type: 'Fee type',
    late_fee_frequency: 'Late fee frequency (days)',
    accumulatedFees: 'Accumulated charges',
    pendingPayment: 'Pending payment',
    paymentsList: 'Request payments',
    breakdownTab: 'Breakdown',
    activityAndComments: 'Activity and comments',
    initialPaymentRequest: 'Initial request',
    paymentLabel: 'Payment',
    balance: 'Balance',
    partialPayment: 'Partial payment',
    partial_payment: 'Partial payment',
    due_date: 'Due date',
    pay_by: 'Due date',
    studentInformation: 'Student information',
    paymentDetail: 'Payment detail',
    tuitionPaymentDetail: 'Tuition payment detail',
    paymentRequest: 'Payment request',
    viewPaymentRequest: 'View payment request',
    registeredPayments: 'Registered payments',
    noPaymentsRegistered: 'No payments registered',
    totalAmount: 'Total amount',
    print: 'Print',
    edit: 'Edit',
    approve: 'Approve',
    reject: 'Reject',
    phone: 'Phone',
    noInformation: 'No information',
    paymentRequestDetail: 'Payment request detail',
    paymentRequestPlaceholder: 'The detail page for request #{id} will be available soon.',
    loadingRequest: 'Loading request...',
    groupLabel: 'Group: {{group}} · Level: {{level}} · Generation: {{generation}}',
    payment_concept_id: 'Payment concept',
    payment_month: 'Tuition month',
    payment_status_id: 'Payment status',
    validated_by_user_id: 'Validated by',
    validated_at: 'Validation date',
    created_at: 'Creation date',
    updated_at: 'Update date',
    payment_request_id: 'Payment request',
    payment_through_id: 'Payment method',
    receipt_path: 'Receipt',
    receipt_file_name: 'Receipt name',
    payment_date: 'Payment date',
    close: 'Close',
    addPayment: 'Add payment',
    noPermissionTitle: 'No permissions',
    noPermissionDescription: 'You do not have the required permissions to access this section. Please contact your administrator.',
    noReceiptPermission: 'You do not have permission to upload or modify the receipt.',
    confirmRejectPayment: 'Do you want to reject this payment',
    cancel: 'Cancel',
    accept: 'Accept',
    confirm: 'Confirm',
    save: 'Save',
    saving: 'Saving...',
    printerSettingsTitle: 'Printer settings',
    printerSettingsDescription: 'Configure a receipt printer when using the desktop app.',
    printerNotAvailableBrowser: 'Printing is only available in the desktop app.',
    printerNotAvailableDesktop: 'Printing is not available right now.',
    printerPermissionRequired: 'Printer permissions are missing. Check device permissions.',
    printerBridgeMissingFeatures: 'Printing integration is not ready in this installation.',
    printerLoading: 'Loading printers...',
    printerEmptyList: 'No printers found. Connect or install a printer and try again.',
    printerDropdownLabel: 'Receipt printer',
    printerDefaultSuffix: 'default',
    printerSaveButton: 'Save selection',
    printerTestButton: 'Test print',
    printerTesting: 'Sending test...',
    areYouSureCloseRequest: 'Are you sure you want to close this request?',
    areYouSureCancelRequest: 'Are you sure you want to cancel this request?',
    school: 'School',
    scholarLevel: 'Scholar level',
    metaSchoolCard: 'Add or update the school information.',
    name: 'Name',
    firstName: 'Name',
    lastNameFather: 'Last name',
    lastNameMother: 'Second last name',
    birthDate: 'Birth date',
    phoneNumber: 'Phone number',
    taxId: 'Tax ID',
    curp: 'CURP',
    institutionalEmail: 'Institutional email',
    personalEmail: 'Personal email',
    street: 'Street',
    extNumber: 'Outer number',
    intNumber: 'Interior number',
    suburb: 'Suburb',
    locality: 'Locality',
    municipality: 'Municipality',
    state: 'State',
    reference: 'Reference',
    enrollment: 'Enrollment',
    mainData: 'Main data',
    address: 'Address',
    addressHelper: 'Student address.',
    generation: 'Generation',
    class: 'Class',
    level: 'Level',
    'status-1': 'Not validated',
    'status-2': 'Pending validation',
    'status-3': 'Validated',
    'status-4': 'Rejected',
    'status-5': 'Paid',
    'status-6': 'Unpaid',
    'status-7': 'Closed',
    'status-8': 'Canceled',
    'partialPayment-0': 'No',
    'partialPayment-1': 'Yes',
    success: 'Success',
    warning: 'Warning',
    neutral: 'No status',
    logsTitle: 'Execution history',
    registerPaymentTitle: 'Register payment',
    registerPaymentDescription: 'Enter the payment information to continue.',
    enterValidAmount: 'Enter a valid amount',
    amountMustCoverPending: 'The amount must cover the pending balance.',
    paymentMethodRequired: 'Select a payment method',
    noActiveSession: 'No active session',
    paymentRegisterError: 'The payment could not be registered',
    paymentRegisterSuccess: 'Payment successfully registered',
    printTicketPromptTitle: 'Print ticket?',
    printTicketPromptText: 'The payment was registered successfully. Do you want to print the ticket?',
    printTicketConfirm: 'Print ticket',
    printTicketSkip: 'Skip',
    printTicketSuccessTitle: 'Ticket sent',
    printTicketSuccess: 'The ticket was sent to the printer.',
    printTicketErrorTitle: 'Could not print',
    printTicketError: 'An error occurred while sending the ticket to the printer.',
    printTicketUnavailable: 'Printing is only available on the desktop app or no printer is configured.',
    paymentRegisterUnexpected: 'An error occurred while registering the payment',
    registerPayment: 'Register payment',
    registeringPayment: 'Registering...',
    addAdditionalInformation: 'Add additional information',
    selectedFile: 'Selected file',
    createManualPayment: 'Create manual payment',
    createManualPaymentDescription: 'Register a payment by filling out all fields.',
    studentRequired: 'Select a student',
    paymentConceptRequired: 'Select a payment concept',
    paymentMonthRequired: 'Select the payment month',
    createPayment: 'Create payment',
    register: 'Enrollment',
    group: 'Group',
    username: 'Username',
    password: 'Password',
    clear: 'Clear',
    searching: 'Searching...',
    yes: 'Yes',
    no: 'No',
    scheduleRequest: 'Schedule a Request',
    scheduleRequestDescription: 'Create scheduled payment request rules',
    createSingleRequest: 'Create a Request',
    createSingleRequestDescription: 'Create a payment request',
    updatePermissionTitle: 'Are you sure you want to change the permissions?',
    updatePermissionConfirmation: 'You can restore the permissions at any time.',
    createClass: 'Create Class',
    createStudent: 'Create Student',
    studentsBulkUploadTitle: 'Students bulk upload',
    studentsBulkUploadSubtitle: 'Upload a CSV file to validate and create students.',
    studentsBulkUploadInvalidFile: 'Only CSV files are allowed.',
    studentsBulkUploadEmptyFile: 'The file is empty.',
    studentsBulkUploadHeaderError: 'The file does not include the required headers.',
    studentsBulkUploadLimitError: 'The file can only include up to 100 records.',
    studentsBulkUploadDrag: 'Drag and drop your CSV file here',
    studentsBulkUploadSelect: 'Or click to select a file.',
    studentsBulkUploadDownload: 'Download template',
    studentsBulkUploadReport: 'Download report',
    studentsBulkUploadValid: '{count} valid',
    studentsBulkUploadInvalid: '{count} with errors',
    studentsBulkUploadValidating: 'Validating...',
    studentsBulkUploadCreate: 'Create valid students',
    studentsBulkUploadCreating: 'Creating...',
    studentsBulkUploadRequired: 'Field {field} is required.',
    studentsBulkUploadDuplicate: '{field} duplicated in file.',
    studentsBulkUploadValidationError: 'The record could not be validated on the server.',
    studentsBulkUploadExists: 'The record already exists on the server.',
    studentsBulkUploadNoValid: 'There are no valid records to create.',
    studentsBulkUploadHideLog: 'Hide log',
    studentsBulkUploadShowLog: 'Show log',
    studentsBulkUploadRow: 'Row {row}',
    studentsBulkUploadMixedTitle: 'There are records with errors',
    studentsBulkUploadMixedMessage: 'Only valid records will be created. Do you want to continue?',
    studentsBulkUploadCreateSuccess: 'Records created successfully.',
    studentsBulkUploadCreateError: 'The records could not be created.',
    studentsBulkUploadStepsTitle: 'Steps to upload',
    studentsBulkUploadStepSchoolTitle: 'Select the school',
    studentsBulkUploadStepSchoolDescription: 'Choose the school to load the available group list.',
    studentsBulkUploadStepGroupTitle: 'Select the group',
    studentsBulkUploadStepGroupDescription: 'Pick the group that will be applied to all uploaded students.',
    studentsBulkUploadStepTemplateTitle: 'Download the template',
    studentsBulkUploadStepTemplateDescription: 'Use the reference CSV file to keep the correct format.',
    studentsBulkUploadStepUploadTitle: 'Upload the CSV file',
    studentsBulkUploadStepUploadDescription: 'Drag or select a file with up to 100 records.',
    studentsBulkUploadHelper: 'Remember to complete all required fields marked with *.',

  },
}

interface LanguageContextValue {
  locale: Locale
  setLocale: (locale: Locale) => void
  t: (key: keyof typeof translations['en']) => string
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

function getInitialLocale(): Locale {
  const match = window.location.pathname.match(/^\/(es|en)(?:\/|$)/)
  if (match) {
    return match[1] as Locale
  }
  return 'es'
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(getInitialLocale())

  const value = useMemo<LanguageContextValue>(() => {
    const t = (key: keyof typeof translations['en']) => translations[locale][key] || key
    return { locale, setLocale, t }
  }, [locale])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return ctx
}
